### ISSUE TITLE
What is the small mistake in the functional example in the readme?

### ISSUE THREAD

**Issue by josegonzalez** [jkseppan/htexpr#3]
In the readme, you say:

> The latter has a small mistake that is in my opinion easy to make by accident, but is completely avoided in the htexpr syntax.

I didn't notice what the mistake was. Would you mind pointing it out for noobs like me? :)

**Comment by jkseppan** [comment]
This line:
```python
html.Tr(html.Th("char"), html.Th("name"), html.Th("category"))
```
is wrong because `html.Tr` is [defined](https://github.com/plotly/dash-html-components/blob/ef43471f03dc088f0860c222fa5166f4a5033b15/dash_html_components/Tr.py#L44) as
```python
def __init__(self, children=None, id=Component.UNDEFINED, n_clicks=Component.UNDEFINED, ...):
```
so the example tries to set `children` to `Th(...)`, `id` to another `Th(...)` and `n_clicks` to a third instance. The line could be fixed like this:
```
html.Tr([html.Th("char"), html.Th("name"), html.Th("category")])
```

**Comment by jkseppan** [comment]
This is now explained in a footnote at https://htexpr.readthedocs.io/en/latest/motivation.html
